### ISSUE TITLE
Naive Question

### ISSUE THREAD

**Issue by joshk6656** [B1naryKill3r/HQSolver#15]
I am curious about this functionality, do you use this to search specific sites, or just google? 

How do you configure your CSE?,

**Comment by B1naryKill3r** [comment]
Just Google, I named this "Naive" because it's Naive :P It counts how much answer words are in the search result.

Google solver, however, uses more advanced techniques to determine the answer. For example, it removes "Stop words" from question etc...

You don't need to configure CSE it should work with default settings, but I configured my CSE to "Search the whole web, but prioritize this website" (don't know how this looks in an English version, I'm not native English speaker):
- en.wikipedia.org/*

If you have your own sources, feel free to use them. More tested sources gives better answers :)

**Comment by B1naryKill3r** [comment]
No response,
Closing, if you have more questions, feel free to reopen :)
